### PR TITLE
docs(readme) : change filepath to url

### PR DESCRIPTION
**Pull request by behzad888**

### CODE REVIEW

**Comment by bloodknight2010** [comment]
```
Error: /home/wymh/projects/APK/app/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:21: error: package android.support.v4.content does not exist
import android.support.v4.content.AsyncTaskLoader;
                                 ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:36: error: cannot find symbol
public class FileLoader extends AsyncTaskLoader<List<File>> {
                                ^
  symbol: class AsyncTaskLoader
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:28: error: package android.support.v4.app does not exist
import android.support.v4.app.FragmentActivity;
                             ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:29: error: package android.support.v4.app does not exist
import android.support.v4.app.FragmentManager;
                             ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:30: error: package android.support.v4.app.FragmentManager does not exist
import android.support.v4.app.FragmentManager.BackStackEntry;
                                             ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:31: error: package android.support.v4.app.FragmentManager does not exist
import android.support.v4.app.FragmentManager.OnBackStackChangedListener;
                                             ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:32: error: package android.support.v4.app does not exist
import android.support.v4.app.FragmentTransaction;
                             ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:45: error: cannot find symbol
public class FileChooserActivity extends FragmentActivity implements
                                         ^
  symbol: class FragmentActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:46: error: cannot find symbol
        OnBackStackChangedListener, FileListFragment.Callbacks {
        ^
  symbol: class OnBackStackChangedListener
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:23: error: package android.support.v4.app does not exist
import android.support.v4.app.ListFragment;
                             ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:24: error: package android.support.v4.app does not exist
import android.support.v4.app.LoaderManager;
                             ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:25: error: package android.support.v4.content does not exist
import android.support.v4.content.Loader;
                                 ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:38: error: cannot find symbol
public class FileListFragment extends ListFragment implements
                                      ^
  symbol: class ListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:39: error: package LoaderManager does not exist
        LoaderManager.LoaderCallbacks<List<File>> {
                     ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:54: error: cannot find symbol
    private FragmentManager mFragmentManager;
            ^
  symbol:   class FragmentManager
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:123: error: cannot find symbol
    public Loader<List<File>> onCreateLoader(int id, Bundle args) {
           ^
  symbol:   class Loader
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:128: error: cannot find symbol
    public void onLoadFinished(Loader<List<File>> loader, List<File> data) {
                               ^
  symbol:   class Loader
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:138: error: cannot find symbol
    public void onLoaderReset(Loader<List<File>> loader) {
                              ^
  symbol:   class Loader
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:53: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:84: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:86: error: cannot find symbol
                if (isReset()) {
                    ^
  symbol:   method isReset()
  location: class FileLoader
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:94: error: cannot find symbol
                if (isStarted())
                    ^
  symbol:   method isStarted()
  location: class FileLoader
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:95: error: cannot find symbol
                        super.deliverResult(data);
                        ^
  symbol:   variable super
  location: class FileLoader
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:101: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:110: error: cannot find symbol
                                        onContentChanged();
                                        ^
  symbol: method onContentChanged()
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:116: error: cannot find symbol
                if (takeContentChanged() || mData == null)
                    ^
  symbol:   method takeContentChanged()
  location: class FileLoader
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:117: error: cannot find symbol
                        forceLoad();
                        ^
  symbol:   method forceLoad()
  location: class FileLoader
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:120: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:122: error: cannot find symbol
                cancelLoad();
                ^
  symbol:   method cancelLoad()
  location: class FileLoader
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:125: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:135: error: method does not override or implement a method from a supertype
        @Override
        ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileLoader.java:137: error: cannot find symbol
                super.onCanceled(data);
                ^
  symbol:   variable super
  location: class FileLoader
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:68: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:70: error: cannot find symbol
        super.onCreate(savedInstanceState);
        ^
  symbol:   variable super
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:72: error: cannot find symbol
        mFragmentManager = getSupportFragmentManager();
                           ^
  symbol:   method getSupportFragmentManager()
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:82: error: cannot find symbol
        setTitle(mPath);
        ^
  symbol:   method setTitle(String)
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:85: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:87: error: cannot find symbol
        super.onPause();
        ^
  symbol:   variable super
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:92: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:94: error: cannot find symbol
        super.onResume();
        ^
  symbol:   variable super
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:99: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:101: error: cannot find symbol
        super.onSaveInstanceState(outState);
        ^
  symbol:   variable super
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:106: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:111: error: cannot find symbol
            BackStackEntry fragment = mFragmentManager.getBackStackEntryAt(count - 1);
            ^
  symbol:   class BackStackEntry
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:117: error: cannot find symbol
        setTitle(mPath);
        ^
  symbol:   method setTitle(String)
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:119: error: cannot find symbol
            invalidateOptionsMenu();
            ^
  symbol:   method invalidateOptionsMenu()
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:122: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:127: error: cannot find symbol
            ActionBar actionBar = getActionBar();
                                  ^
  symbol:   method getActionBar()
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:135: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:143: error: cannot find symbol
        return super.onOptionsItemSelected(item);
               ^
  symbol:   variable super
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:152: error: cannot find symbol
        Context context = getApplicationContext();
                          ^
  symbol:   method getApplicationContext()
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:171: error: cannot find symbol
        Context context = getApplicationContext();
                          ^
  symbol:   method getApplicationContext()
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:177: error: cannot find symbol
                .setTransition(FragmentTransaction.TRANSIT_FRAGMENT_OPEN)
                               ^
  symbol:   variable FragmentTransaction
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:189: error: cannot find symbol
            setResult(RESULT_OK, new Intent().setData(uri));
                      ^
  symbol:   variable RESULT_OK
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:190: error: cannot find symbol
            finish();
            ^
  symbol:   method finish()
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:192: error: cannot find symbol
            setResult(RESULT_CANCELED);
                      ^
  symbol:   variable RESULT_CANCELED
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:193: error: cannot find symbol
            finish();
            ^
  symbol:   method finish()
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:211: error: cannot find symbol
            String packageName = getApplicationContext().getPackageName();
                                 ^
  symbol:   method getApplicationContext()
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:212: error: cannot find symbol
            int errorSelectingFileStringId = getApplicationContext().getResources().getIdentifier("error_selecting_file", "string", packageName);
                                             ^
  symbol:   method getApplicationContext()
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:213: error: cannot find symbol
            String errorSelectingFileStringStr = getApplicationContext().getString(errorSelectingFileStringId);
                                                 ^
  symbol:   method getApplicationContext()
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:215: error: no suitable method found for makeText(FileChooserActivity,String,int)
            Toast.makeText(FileChooserActivity.this, errorSelectingFileStringStr,
                 ^
    method Toast.makeText(Context,CharSequence,int) is not applicable
      (argument mismatch; FileChooserActivity cannot be converted to Context)
    method Toast.makeText(Context,int,int) is not applicable
      (argument mismatch; FileChooserActivity cannot be converted to Context)
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:226: error: cannot find symbol
        registerReceiver(mStorageListener, filter);
        ^
  symbol:   method registerReceiver(BroadcastReceiver,IntentFilter)
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileChooserActivity.java:233: error: cannot find symbol
        unregisterReceiver(mStorageListener);
        ^
  symbol:   method unregisterReceiver(BroadcastReceiver)
  location: class FileChooserActivity
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:70: error: cannot find symbol
        fragment.setArguments(args);
                ^
  symbol:   method setArguments(Bundle)
  location: variable fragment of type FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:75: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:77: error: cannot find symbol
        super.onAttach(activity);
        ^
  symbol:   variable super
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:87: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:89: error: cannot find symbol
        super.onCreate(savedInstanceState);
        ^
  symbol:   variable super
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:91: error: cannot find symbol
        mAdapter = new FileListAdapter(getActivity());
                                       ^
  symbol:   method getActivity()
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:92: error: cannot find symbol
        mPath = getArguments() != null ? getArguments().getString(
                ^
  symbol:   method getArguments()
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:92: error: cannot find symbol
        mPath = getArguments() != null ? getArguments().getString(
                                         ^
  symbol:   method getArguments()
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:97: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:99: error: cannot find symbol
        Context context = getActivity();
                          ^
  symbol:   method getActivity()
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:103: error: cannot find symbol
        setEmptyText(getString(emptyDirectoryId));
                     ^
  symbol:   method getString(int)
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:104: error: cannot find symbol
        setListAdapter(mAdapter);
        ^
  symbol:   method setListAdapter(FileListAdapter)
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:105: error: cannot find symbol
        setListShown(false);
        ^
  symbol:   method setListShown(boolean)
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:107: error: cannot find symbol
        getLoaderManager().initLoader(LOADER_ID, null, this);
        ^
  symbol:   method getLoaderManager()
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:109: error: cannot find symbol
        super.onActivityCreated(savedInstanceState);
        ^
  symbol:   variable super
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:112: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:122: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:124: error: cannot find symbol
        return new FileLoader(getActivity(), mPath);
                              ^
  symbol:   method getActivity()
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:127: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:131: error: cannot find symbol
        if (isResumed())
            ^
  symbol:   method isResumed()
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:132: error: cannot find symbol
            setListShown(true);
            ^
  symbol:   method setListShown(boolean)
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:134: error: cannot find symbol
            setListShownNoAnimation(true);
            ^
  symbol:   method setListShownNoAnimation(boolean)
  location: class FileListFragment
/home/wymh/projects/APK/app/platforms/android/src/com/ipaulpro/afilechooser/FileListFragment.java:137: error: method does not override or implement a method from a supertype
    @Override
    ^
86 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**When I build with cordova I got about that error what happen?**

**Comment by behzad888** [comment]
@caixiangsap please enable issues feature.
@bloodknight2010  please add your problem as issues after enabled

**Comment by caixiangsap** [comment]
seems you did not install "Android Support Library" using Android SDK Manager.

**Review by caixiangsap — APPROVED** [review]

**Comment by bloodknight2010** [comment]
@caixiangsap 
I installed following android library. But I can't. Pls help me  :(
screenshot_20170307_191556
screenshot_20170307_191632
screenshot_20170307_191703
screenshot_20170307_191718
screenshot_20170307_191752

**Pull request merged**
